name: BuoyyShop
version: '1.0'
main: com.github.buoyy.shop.Shop
api-version: '1.21'
depend: [ BuoyyEcon ]
commands:
  shop:
    usage: /shop
    description: Open main menu for BuoyyShop
  file:
    usage: /file
    description: fff